### PR TITLE
fix: check nodeType for dom elements 

### LINKED ISSUE #3: instanceOf(Element) doesn't work in iframe
@merceyz I have noticed a warning with this demo https://material-ui.com/components/drawers/#responsive-drawer which lead my track down to:

https://github.com/merceyz/typescript-to-proptypes/blob/adfcca429fca9b1734e361547d19fb9a79a335be/src/parser.ts#L355-L358

`instanceOf(Element)` doesn't work with different documents, e.g. iframe: https://github.com/facebook/prop-types/issues/240#issuecomment-524997768.

We were able to work around the problem in the Popper component with: https://github.com/mui-org/material-ui/blob/c1c66903b8cc3941d0e110f13f49122effdc0e47/packages/material-ui/src/Popper/Popper.js#L238. 

Any idea on how we could best solve this problem?

### PR DESCRIPTION
**Pull request by merceyz**
Fixes #3 
Closes #11 

Implements proper handling of `Element` and `HTMLElement` types by checking their nodeType

### CODE REVIEW

**Review by eps1lon — COMMENTED** [review]
As I said before most of the use cases don't care about the realm of the element. `Node.nodeType` is simpler and doesn't require ownerDocument lookups.

File: test/generator/html-elements/output.js [hunk 1]
```diff
@@ -0,0 +1,115 @@
+Foo.propTypes = {
+	bothTypes: PropTypes.oneOfType([
```
Comment (oliviertassinari) [inline test/generator/html-elements/output.js]: Maybe it would be better if we could replace this code with a custom element prop-types hosted in `@material-ui/core/utils`.

Comment (merceyz) [reply test/generator/html-elements/output.js]: With https://github.com/merceyz/typescript-to-proptypes/pull/10 that is an option

**Comment by merceyz** [comment]
@eps1lon @oliviertassinari Does this work for you?

**Review by oliviertassinari — APPROVED** [review]
